version: '3'
services:
  cassandra1:
    hostname: cassandra1
    image: cassandra:latest
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
  cassandra2:
    hostname: cassandra2
    image: cassandra:latest
    command: /bin/bash -c "sleep 30 && echo '--- Pausing to let system catch up... --->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra1
    links:
      - cassandra1:cassandra
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    depends_on:
      - cassandra1